FROM python:3.11-alpine

WORKDIR /app

ENV APP_ENV=production
ENV APP_MESSAGE="default message from Dockerfile"

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY app.py .

EXPOSE 5000

CMD ["python", "app.py"]
