#!/bin/bash

if [ -d $HOME/performance ]; then
	echo "Preformance directory exist"
	else
	mkdir $HOME/performance
fi

free >> $HOME/performance/memory.log # To append the output of the free command to the memory.log file
